### ISSUE TITLE
Feedback of 1st Assignment

### ISSUE THREAD

**Issue by Adam2092** [LaizFigueroa/DIT168#14]
- It is highly recommended to avoid uploading Docker images and any "build" folders to gitHub.
- If you use the file name "Dockerfile" without ".txt" extension, and put it in the root folder of your project, it will be detected by the command "docker build" directly by default, without using "-f" argument and "dockerfile" folder as well.
- Please consider using only one source file folder, traditionally named "src" if you would like.

From Yue Kang

**Comment by LaizFigueroa** [comment]
Your comments were taken into account and the changes were integrated into our repo.
